### Imports

In [1]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.neural_network import MLPClassifier
import warnings

warnings.filterwarnings('ignore')

### Importando dados

In [2]:
df = pd.read_excel('../datasets/Chamados_Completo_BOW.xlsx')
display(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2610 entries, 0 to 2609
Columns: 1001 entries, label to zer
dtypes: int64(1001)
memory usage: 19.9 MB

None

,label,a,aba,abaix,abert,abr,aca,acerc,acess,acim,...,vot,web,wif,word,www,wwwreleas,xavi,xml,yusk,zer
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

- Labels

In [3]:
y = df['label']
y.head()

0    0
1    1
2    0
3    0
4    1
Name: label, dtype: int64

- Features

In [4]:
X = df.drop(columns=['label'])
X.head()

,a,aba,abaix,abert,abr,aca,acerc,acess,acim,aco,...,vot,web,wif,word,www,wwwreleas,xavi,xml,yusk,zer
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Validação cruzada

- Modelos

In [5]:
# Definindo modelos
names = ["k-Nearest Neighbors", "Árvores de decisão", "Naive Bayes", "MultiLayer Perceptron (MLP)"]

classifiers = [
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    MultinomialNB(),
    MLPClassifier()
]

models = zip(names, classifiers)
models

- Cross validation

In [6]:
for name, model in models:
    print(name, '\n')
    scores = cross_val_score(model, X, y, cv=10, scoring='accuracy')
    print("Accuracy scores: ", scores, '\n')
    print('========================================================')

k-Nearest Neighbors

Accuracy scores:  [0.80152672 0.87022901 0.86641221 0.79770992 0.79310345 0.82375479
 0.8        0.81923077 0.86153846 0.83461538]

========================================================
Árvores de decisão

Accuracy scores:  [0.84732824 0.88167939 0.88931298 0.86259542 0.86590038 0.83141762
 0.9        0.88076923 0.91538462 0.85384615]

========================================================
Naive Bayes

Accuracy scores:  [0.88167939 0.91984733 0.86259542 0.85496183 0.87739464 0.86590038
 0.89230769 0.92692308 0.92307692 0.89230769]

========================================================
MultiLayer Perceptron (MLP)

Accuracy scores:  [0.87022901 0.90458015 0.88549618 0.8740458  0.90421456 0.88505747
 0.91153846 0.91538462 0.93076923 0.86923077]

========================================================